### ISSUE TITLE
ValueError: could not broadcast input array from shape (15) into shape (20)

### ISSUE THREAD

**Issue by outlk** [tsutterley/read-cryosat-2#14]
Hello, thank you for your python toolkit for reading cryosat-2 data. Yesterday i donwloaded this repository and used it to read  "CS_OFFL_SIR_GDR_2__20200401T020323_20200401T034237_D001.nc" .
An error occured at Line 719 of read_cryosat_L2.py,. The detail is "ValueError: could not broadcast input array from shape (15) into shape (20)". So how to fix it?

**Comment by tsutterley** [comment]
Hi @outlk this is an interesting error.  within the Baseline D Level-2 files there's an index variable called `ind_first_meas_20hz_01`.  This is a pointer variable that maps between the 20Hz and the 1Hz data.  Interestingly, the indices it refers to in the GDR data are outside the range of data for an individual file.  I haven't seen this in any other Level-2 dataset.  I'm putting in a PR to patch this right now.

**Comment by outlk** [comment]
Hi, @tsutterley, i have investigated the Baseline D Level-2 GDR data for variables of time_cor_01, ind_first_meas_20hz_01, num_valid_01, time_20_ku, ind_meas_1hz_20_ku. I found that the values for ind_first_meas_20hz_01 in GDR files maybe are with incorrect values because they are all multiples of 20, which is not possible introduced by the values of num_valid_01 (not all 20). So i infer the ind_first_meas_20hz_01 must be re-mapped manually according to time_cor_01 and time_20_ku.

[submit.zip](https://github.com/tsutterley/read-cryosat-2/files/4810597/submit.zip)

**Comment by tsutterley** [comment]
Hi @outlk you're right the underlying issue was different from what I thought Friday.  I remapped the 20Hz index using the 1Hz mapping and it should be good to go once i put in the PR
