### ISSUE TITLE
USO Correction as Unsigned Integer

### ISSUE THREAD

**Issue by sfons** [tsutterley/read-cryosat-2#2]
The USO Correction can (apparently) be negative, so reading in as an unsigned integer leads to anomalous corrected window delay time values and subsequent anomalous elevations.

A sample file over Antarctic sea ice showed the following:
![USO_corr](https://user-images.githubusercontent.com/38258174/56661506-de63db80-666f-11e9-83f8-4b6cd00f46fe.png)
where black was found using read_cryosat_L1b.py and teal was found using ESA's CryoSat MATLAB readers.

The teal line can be reproduced when changing lines 49, 318, 495, and 778 of read_cryosat_L1b.py to be signed integers.

**Comment by tsutterley** [comment]
Should be fixed!  Thanks for pointing this out @sfons
