### ISSUE TITLE
Reading GDR_2 data

### ISSUE THREAD

**Issue by gepo1989** [tsutterley/read-cryosat-2#3]
I encountered an issue when reading in GDR_2 data.
I had to change line 530 in read_cryosat_L2.py to
`	regex_patterns.append(b'DS_NAME\="SIR_GDR_2_[\s+]*"')`
with the '_' after 'GDR_2'.
Thanks for sharing this!

**Comment by tsutterley** [comment]
Hopefully the changes fix your problems @gepo1989 
Thanks for pointing it out!
